spring:
  application:
    name: service-data-com.github.sync
  messages:
    basename: i18n/messages
  profiles:
    active: ${ENVIRONMENT:dev}
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: ${TZ:Asia/Shanghai}
  redis:
    host: localhost
    port: 6379
    database: 14

data:
  sync:
    canal:
      ipv4: localhost
      port: 11111